In [2]:
import pandas as pd
import numpy as np
import country_converter as cococ
from pathlib import Path

In [3]:
DATA = Path(r'C:\Users\indra\Desktop\Thesis\Final project for thesis\Data')

consumption    = DATA / 'National_Fossil_Carbon_Emissions_2025_consumption_emission.xlsx'
population     = DATA / 'Population_with_ISO3.csv'
gdp_per_capita = DATA / 'API_NY.GDP.PCAP.PP.KD_DS2_en_csv_v2_33608.csv'
trade_openess  = DATA / 'API_NE.TRD.GNFS.ZS_DS2_en_csv_v2_171.csv'

out_final = DATA / 'data_final.csv'


EDGAR = DATA / 'EDGAR_1970_2024_production_emission.xlsx'

In [4]:
pd.set_option('display.max_rows', None)

## Consumption and production data cleaning, converting to long format, adding iso3 code and integration

In [5]:
df_c= pd.read_excel(consumption, sheet_name='Consumption Emissions', skiprows=8)
df_p= pd.read_excel(consumption, sheet_name='Territorial Emissions', skiprows=11)

In [6]:
df_c.head()

,Unnamed: 0,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Central America,Europe,Middle East,North America,Oceania,South America,International Shipping,International Aviation,Statistical Difference,World
0,1990,NaN,1.521142,NaN,NaN,NaN,NaN,NaN,31.534647,1.718126,...,27.651485,2160.772537,236.166776,1603.565787,75.966392,161.764237,97.945741,51.581993,1.534772e-12,6204.187685
1,1991,NaN,1.259848,NaN,NaN,NaN,NaN,NaN,33.842289,1.323240,...,26.479337,2116.915514,256.960227,1587.351971,76.267238,166.615843,94.244590,53.863925,1.304380e+02,6333.403645
2,1992,NaN,0.798289,NaN,NaN,NaN,NaN,NaN,35.863287,1.039043,...,25.889646,1834.040991,288.842443,1652.287734,77.435693,172.735292,91.447095,59.703935,-1.989520e-13,6146.403948
3,1993,NaN,0.730026,NaN,NaN,NaN,NaN,NaN,34.552463,0.516293,...,26.693117,1813.570118,297.916326,1660.811385,77.655632,179.642928,90.458482,61.679735,0.000000e+00,6209.026223
4,1994,NaN,0.645564,NaN,NaN,NaN,NaN,NaN,34.683976,0.514092,...,27.808745,1769.092533,306.828160,1691.698688,80.418479,180.865685,94.105042,65.509969,5.115908e-13,6270.359809

In [ ]:
drop_regions = [
    'World', 'Statistical Difference', 'International Shipping', 'International Aviation',
    'Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania',
    'Central America', 'Middle East', 'OECD', 'Non-OECD', 'EU27',
    'KP Annex B', 'Non KP Annex B',  
]

In [8]:
df_c= df_c.drop(columns=drop_regions)
df_p= df_p.drop(columns=drop_regions)

In [9]:
df_c=df_c.rename(columns={'Unnamed: 0': 'Year'})
df_p=df_p.rename(columns={'Unnamed: 0': 'Year'})
#df_c=df_c.dropna()
#df_p=df_p.dropna()

In [10]:
df_c.head()

,Year,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,USA,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,Yemen,Zambia,Zimbabwe
0,1990,NaN,1.521142,NaN,NaN,NaN,NaN,NaN,31.534647,1.718126,...,1378.640828,1.311983,NaN,NaN,23.525387,6.353081,NaN,NaN,0.431041,3.513608
1,1991,NaN,1.259848,NaN,NaN,NaN,NaN,NaN,33.842289,1.323240,...,1357.636447,1.466874,NaN,NaN,24.473680,6.322552,NaN,NaN,0.505207,3.470919
2,1992,NaN,0.798289,NaN,NaN,NaN,NaN,NaN,35.863287,1.039043,...,1415.812776,1.660174,NaN,NaN,23.695246,6.320101,NaN,NaN,0.547335,3.661460
3,1993,NaN,0.730026,NaN,NaN,NaN,NaN,NaN,34.552463,0.516293,...,1426.606297,1.526427,NaN,NaN,27.428083,6.867454,NaN,NaN,0.569660,3.316654
4,1994,NaN,0.645564,NaN,NaN,NaN,NaN,NaN,34.683976,0.514092,...,1452.640773,1.463222,NaN,NaN,25.361186,8.035245,NaN,NaN,0.571513,3.454661

**Checking the Consumption Emission** `Year` is now a renamed.

In [11]:
df_p.head()

,Year,Afghanistan,Albania,Algeria,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,USA,Uruguay,Uzbekistan,Vanuatu,Venezuela,Viet Nam,Wallis and Futuna Islands,Yemen,Zambia,Zimbabwe
0,1850,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000069,...,5.402,NaN,0.000807,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,1851,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,...,6.723,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,1852,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,...,7.312,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,1853,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,...,8.232,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,1854,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.000000,...,9.050,NaN,0.000000,NaN,NaN,0.0,NaN,NaN,NaN,NaN

**Checking the Production Emission.** Same number of columns as the consumption
emission, but the series starts in 1850.

In [ ]:

C_TO_CO2 = 3.664


def to_long_format(df, value_name):
    
    return df.melt(id_vars='Year', var_name='Country', value_name=value_name)


def carbon_to_co2(df, value_name):
    
    df = df.copy()
    df[value_name] = df[value_name] * C_TO_CO2
    return df


df_c_long = carbon_to_co2(to_long_format(df_c, 'Consumption_Emissions'), 'Consumption_Emissions')
df_p_long = carbon_to_co2(to_long_format(df_p, 'Production_Emissions'), 'Production_Emissions')


**On the factor:** GCP reports Mt of *carbon*; this thesis reports Mt of *CO₂*.
The stoichiometric ratio is 44/12 = 3.6667, but GCB publishes 3.664, so 3.664 is
kept to stay consistent with the source. Every emissions figure downstream —
`transfer` included — is therefore in **Mt CO₂**.

In [13]:
df_c_long.head()

   Year      Country  Consumption_Emissions
0  1990  Afghanistan                    NaN
1  1991  Afghanistan                    NaN
2  1992  Afghanistan                    NaN
3  1993  Afghanistan                    NaN
4  1994  Afghanistan                    NaN

**Consumption in long format.** One row per country-year. The leading `NaN`s are
expected: melting a wide frame materialises every country × year combination,
including the ones with no data.

In [14]:
df_p_long.head()

   Year      Country  Production_Emissions
0  1850  Afghanistan                   NaN
1  1851  Afghanistan                   NaN
2  1852  Afghanistan                   NaN
3  1853  Afghanistan                   NaN
4  1854  Afghanistan                   NaN

**Production in long format.** Same structure, far more rows, because this series
reaches back to 1850.

In [15]:
print("Shape of df_c_long:", df_c_long.shape)
print("Shape of df_p_long:", df_p_long.shape)
print("Data types of df_c_long:", df_c_long.dtypes)
print("Data types of df_p_long:", df_p_long.dtypes)

Shape of df_c_long: (7490, 3)
Shape of df_p_long: (37450, 3)
Data types of df_c_long: Year                       int64
Country                      str
Consumption_Emissions    float64
dtype: object
Data types of df_p_long: Year                      int64
Country                     str
Production_Emissions    float64
dtype: object

**Pre-cleaning size check.** 7,560 vs 37,800 rows — the gap is almost entirely
the extra 140 years of production history plus the empty combinations from the melt.

In [17]:
print("Shape of df_c_long:", df_c_long.shape)
print("Shape of df_p_long:", df_p_long.shape)
print("Data types of df_c_long:", df_c_long.dtypes)
print("Data types of df_p_long:", df_p_long.dtypes)

Shape of df_c_long: (7490, 3)
Shape of df_p_long: (37450, 3)
Data types of df_c_long: Year                       int64
Country                      str
Consumption_Emissions    float64
dtype: object
Data types of df_p_long: Year                      int64
Country                     str
Production_Emissions    float64
dtype: object

**Post-cleaning size check.** 7,560 → 4,135 and 37,800 → 25,385.

In [18]:
df_c_long.head()

   Year      Country  Consumption_Emissions
0  1990  Afghanistan                    NaN
1  1991  Afghanistan                    NaN
2  1992  Afghanistan                    NaN
3  1993  Afghanistan                    NaN
4  1994  Afghanistan                    NaN

**Spot-check.** Albania 1990 survives with a real value, confirming the drop hit
only the empty rows.

In [19]:
cc = cococ.CountryConverter()

for df in (df_c_long, df_p_long):
    df['ISO3'] = cc.convert(names=df['Country'], to='ISO3')

unmatched_c = df_c_long.loc[df_c_long['ISO3'].isna(), 'Country'].unique()
print('Unmatched in consumption:', unmatched_c)

unmatched_p = df_p_long.loc[df_p_long['ISO3'].isna(), 'Country'].unique()
print('Unmatched in production:', unmatched_p)

Unmatched in consumption: <StringArray>
[]
Length: 0, dtype: str
Unmatched in production: <StringArray>
[]
Length: 0, dtype: str

In [21]:
print(df_c_long.loc[df_c_long['Consumption_Emissions'].isna(), ['Country', 'Year']])

                                Country  Year
0                           Afghanistan  1990
1                           Afghanistan  1991
2                           Afghanistan  1992
3                           Afghanistan  1993
4                           Afghanistan  1994
5                           Afghanistan  1995
6                           Afghanistan  1996
7                           Afghanistan  1997
8                           Afghanistan  1998
9                           Afghanistan  1999
10                          Afghanistan  2000
11                          Afghanistan  2001
12                          Afghanistan  2002
13                          Afghanistan  2003
14                          Afghanistan  2004
15                          Afghanistan  2005
16                          Afghanistan  2006
17                          Afghanistan  2007
18                          Afghanistan  2008
19                          Afghanistan  2009
20                          Afghanistan  2010
21                          Afghanistan  2011
22                          Afghanistan  2012
23                          Afghanistan  2013
24                          Afghanistan  2014
25                          Afghanistan  2015
26                          Afghanistan  2016
27                          Afghanistan  2017
28                          Afghanistan  2018
29                          Afghanistan  2019
30                          Afghanistan  2020
31                          Afghanistan  2021
32                          Afghanistan  2022
33                          Afghanistan  2023
34                          Afghanistan  2024
69                              Albania  2024
70                              Algeria  1990
71                              Algeria  1991
72                              Algeria  1992
73                              Algeria  1993
74                              Algeria  1994
75                              Algeria  1995
76                              Algeria  1996
77                              Algeria  1997
78                              Algeria  1998
79                              Algeria  1999
80                              Algeria  2000
81                              Algeria  2001
82                              Algeria  2002
83                              Algeria  2003
84                              Algeria  2004
85                              Algeria  2005
86                              Algeria  2006
87                              Algeria  2007
88                              Algeria  2008
89                              Algeria  2009
90                              Algeria  2010
91                              Algeria  2011
92                              Algeria  2012
93                              Algeria  2013
94                              Algeria  2014
95                              Algeria  2015
96                              Algeria  2016
97                              Algeria  2017
98                              Algeria  2018
99                              Algeria  2019
100                             Algeria  2020
101                             Algeria  2021
102                             Algeria  2022
103                             Algeria  2023
104                             Algeria  2024
105                             Andorra  1990
106                             Andorra  1991
107                             Andorra  1992
108                             Andorra  1993
109                             Andorra  1994
110                             Andorra  1995
111                             Andorra  1996
112                             Andorra  1997
113                             Andorra  1998
114                             Andorra  1999
115                             Andorra  2000
116                             Andorra  2001
117                             Andorra  2002
118                             Andorra  2003
119                             Andorra  2004
120                             Andorra  2005
121                             Andorra  2006
122                             Andorra  2007
123                             Andorra  2008
124                             Andorra  2009
125                             Andorra  2010
126                             Andorra  2011
127                             Andorra  2012
128                             Andorra  2013
129                             Andorra  2014
130                             Andorra  2015
131                             Andorra  2016
132                             Andorra  2017
133                             Andorra  2018
134                             Andorra  2019
135                             Andorra  2020
136                             Andorra  2021
137                             Andorra  2022
138                             Andorra  2023
139                             Andorra  2024
140                              Angola  1990
141                              Angola  1991
142                              Angola  1992
143                              Angola  1993
144                              Angola  1994
145                              Angola  1995
146                              Angola  1996
147                              Angola  1997
148                              Angola  1998
149                              Angola  1999
150                              Angola  2000
151                              Angola  2001
152                              Angola  2002
153                              Angola  2003
154                              Angola  2004
155                              Angola  2005
156                              Angola  2006
157                              Angola  2007
158                              Angola  2008
159                              Angola  2009
160                              Angola  2010
161                              Angola  2011
162                              Angola  2012
163                              Angola  2013
164                              Angola  2014
165                              Angola  2015
166                              Angola  2016
167                              Angola  2017
168                              Angola  2018
169                              Angola  2019
170                              Angola  2020
171                              Angola  2021
172                              Angola  2022
173                              Angola  2023
174                              Angola  2024
175                            Anguilla  1990
176                            Anguilla  1991
177                            Anguilla  1992
178                            Anguilla  1993
179                            Anguilla  1994
180                            Anguilla  1995
181                            Anguilla  1996
182                            Anguilla  1997
183                            Anguilla  1998
184                            Anguilla  1999
185                            Anguilla  2000
186                            Anguilla  2001
187                            Anguilla  2002
188                            Anguilla  2003
189                            Anguilla  2004
190                            Anguilla  2005
191                            Anguilla  2006
192                            Anguilla  2007
193                            Anguilla  2008
194                            Anguilla  2009
195                            Anguilla  2010
196                            Anguilla  2011
197                            Anguilla  2012
198                            Anguilla  2013
199                            Anguilla  2014
200                            Anguilla  2015
201                            Anguilla  2016
202                            Anguilla  2017
203                            Anguilla  2018
204                            Anguilla  2019
205                            Anguilla  2020
206                            Anguilla  2021
207                            Anguilla  2022
208                            Anguilla  2023
209                            Anguilla  2024
210                 Antigua and Barbuda  1990
211                 Antigua and Barbuda  1991
212                 Antigua and Barbuda  1992
213                 Antigua and Barbuda  1993
214                 Antigua and Barbuda  1994
215                 Antigua and Barbuda  1995
216                 Antigua and Barbuda  1996
217                 Antigua and Barbuda  1997
218                 Antigua and Barbuda  1998
219                 Antigua and Barbuda  1999
220                 Antigua and Barbuda  2000
221                 Antigua and Barbuda  2001
222                 Antigua and Barbuda  2002
223                 Antigua and Barbuda  2003
224                 Antigua and Barbuda  2004
225                 Antigua and Barbuda  2005
226                 Antigua and Barbuda  2006
227                 Antigua and Barbuda  2007
228                 Antigua and Barbuda  2008
229                 Antigua and Barbuda  2009
230                 Antigua and Barbuda  2010
231                 Antigua and Barbuda  2011
232                 Antigua and Barbuda  2012
233                 Antigua and Barbuda  2013
234                 Antigua and Barbuda  2014
235                 Antigua and Barbuda  2015
236                 Antigua and Barbuda  2016
237                 Antigua and Barbuda  2017
238                 Antigua and Barbuda  2018
239                 Antigua and Barbuda  2019
240                 Antigua and Barbuda  2020
241                 Antigua and Barbuda  2021
242                 Antigua and Barbuda  2022
243                 Antigua and Barbuda  2023
244                 Antigua and Barbuda  2024
279                           Argentina  2024
314                             Armenia  2024
315                               Aruba  1990
316                               Aruba  1991
317                               Aruba  1992
318                               Aruba  1993
319                               Aruba  1994
320                               Aruba  1995
321                               Aruba  1996
322                               Aruba  1997
323                               Aruba  1998
324                               Aruba  1999
325                               Aruba  2000
326                               Aruba  2001
327                               Aruba  2002
328                               Aruba  2003
329                               Aruba  2004
330                               Aruba  2005
331                               Aruba  2006
332                               Aruba  2007
333                               Aruba  2008
334                               Aruba  2009
335                               Aruba  2010
336                               Aruba  2011
337                               Aruba  2012
338                               Aruba  2013
339                               Aruba  2014
340                               Aruba  2015
341                               Aruba  2016
342                               Aruba  2017
343                               Aruba  2018
344                               Aruba  2019
345                               Aruba  2020
346                               Aruba  2021
347                               Aruba  2022
348                               Aruba  2023
349                               Aruba  2024
384                           Australia  2024
419                             Austria  2024
454                          Azerbaijan  2024
455                             Bahamas  1990
456                             Bahamas  1991
457                             Bahamas  1992
458                             Bahamas  1993
459                             Bahamas  1994
460                             Bahamas  1995
461                             Bahamas  1996
462                             Bahamas  1997
463                             Bahamas  1998
464                             Bahamas  1999
465                             Bahamas  2000
466                             Bahamas  2001
467                             Bahamas  2002
468                             Bahamas  2003
469                             Bahamas  2004
470                             Bahamas  2005
471                             Bahamas  2006
472                             Bahamas  2007
473                             Bahamas  2008
474                             Bahamas  2009
475                             Bahamas  2010
476                             Bahamas  2011
477                             Bahamas  2012
478                             Bahamas  2013
479                             Bahamas  2014
480                             Bahamas  2015
481                             Bahamas  2016
482                             Bahamas  2017
483                             Bahamas  2018
484                             Bahamas  2019
485                             Bahamas  2020
486                             Bahamas  2021
487                             Bahamas  2022
488                             Bahamas  2023
489                             Bahamas  2024
524                             Bahrain  2024
559                          Bangladesh  2024
560                            Barbados  1990
561                            Barbados  1991
562                            Barbados  1992
563                            Barbados  1993
564                            Barbados  1994
565                            Barbados  1995
566                            Barbados  1996
567                            Barbados  1997
568                            Barbados  1998
569                            Barbados  1999
570                            Barbados  2000
571                            Barbados  2001
572                            Barbados  2002
573                            Barbados  2003
574                            Barbados  2004
575                            Barbados  2005
576                            Barbados  2006
577                            Barbados  2007
578                            Barbados  2008
579                            Barbados  2009
580                            Barbados  2010
581                            Barbados  2011
582                            Barbados  2012
583                            Barbados  2013
584                            Barbados  2014
585                            Barbados  2015
586                            Barbados  2016
587                            Barbados  2017
588                            Barbados  2018
589                            Barbados  2019
590                            Barbados  2020
591                            Barbados  2021
592                            Barbados  2022
593                            Barbados  2023
594                            Barbados  2024
629                             Belarus  2024
664                             Belgium  2024
665                              Belize  1990
666                              Belize  1991
667                              Belize  1992
668                              Belize  1993
669                              Belize  1994
670                              Belize  1995
671                              Belize  1996
672                              Belize  1997
673                              Belize  1998
674                              Belize  1999
675                              Belize  2000
676                              Belize  2001
677                              Belize  2002
678                              Belize  2003
679                              Belize  2004
680                              Belize  2005
681                              Belize  2006
682                              Belize  2007
683                              Belize  2008
684                              Belize  2009
685                              Belize  2010
686                              Belize  2011
687                              Belize  2012
688                              Belize  2013
689                              Belize  2014
690                              Belize  2015
691                              Belize  2016
692                              Belize  2017
693                              Belize  2018
694                              Belize  2019
695                              Belize  2020
696                              Belize  2021
697                              Belize  2022
698                              Belize  2023
699                              Belize  2024
734                               Benin  2024
735                             Bermuda  1990
736                             Bermuda  1991
737                             Bermuda  1992
738                             Bermuda  1993
739                             Bermuda  1994
740                             Bermuda  1995
741                             Bermuda  1996
742                             Bermuda  1997
743                             Bermuda  1998
744                             Bermuda  1999
745                             Bermuda  2000
746                             Bermuda  2001
747                             Bermuda  2002
748                             Bermuda  2003
749                             Bermuda  2004
750                             Bermuda  2005
751                             Bermuda  2006
752                             Bermuda  2007
753                             Bermuda  2008
754                             Bermuda  2009
755                             Bermuda  2010
756                             Bermuda  2011
757                             Bermuda  2012
758                             Bermuda  2013
759                             Bermuda  2014
760                             Bermuda  2015
761                             Bermuda  2016
762                             Bermuda  2017
763                             Bermuda  2018
764                             Bermuda  2019
765                             Bermuda  2020
766                             Bermuda  2021
767                             Bermuda  2022
768                             Bermuda  2023
769                             Bermuda  2024
770                              Bhutan  1990
771                              Bhutan  1991
772                              Bhutan  1992
773                              Bhutan  1993
774                              Bhutan  1994
775                              Bhutan  1995
776                              Bhutan  1996
777                              Bhutan  1997
778                              Bhutan  1998
779                              Bhutan  1999
780                              Bhutan  2000
781                              Bhutan  2001
782                              Bhutan  2002
783                              Bhutan  2003
784                              Bhutan  2004
785                              Bhutan  2005
786                              Bhutan  2006
787                              Bhutan  2007
788                              Bhutan  2008
789                              Bhutan  2009
790                              Bhutan  2010
791                              Bhutan  2011
792                              Bhutan  2012
793                              Bhutan  2013
794                              Bhutan  2014
795                              Bhutan  2015
796                              Bhutan  2016
797                              Bhutan  2017
798                              Bhutan  2018
799                              Bhutan  2019
800                              Bhutan  2020
801                              Bhutan  2021
802                              Bhutan  2022
803                              Bhutan  2023
804                              Bhutan  2024
805   Bonaire, Saint Eustatius and Saba  1990
806   Bonaire, Saint Eustatius and Saba  1991

**Attach ISO3 codes.** The four sources spell countries differently
("Viet Nam" vs "Vietnam", "Korea, Rep." vs "South Korea"), so name-based merging
would silently lose countries. ISO3 is the join key everywhere downstream.

In [22]:
df_c_long.dropna(subset=['Consumption_Emissions'], inplace=True)
df_p_long.dropna(subset=['Production_Emissions'], inplace=True)

In [23]:
df_c_long.head()

    Year  Country  Consumption_Emissions ISO3
35  1990  Albania               5.573464  ALB
36  1991  Albania               4.616082  ALB
37  1992  Albania               2.924931  ALB
38  1993  Albania               2.674815  ALB
39  1994  Albania               2.365348  ALB

**Consumption data with ISO3.** Albania → `ALB`.

In [24]:
df_p_long.head()

     Year      Country  Production_Emissions ISO3
99   1949  Afghanistan              0.014656  AFG
100  1950  Afghanistan              0.084272  AFG
101  1951  Afghanistan              0.091600  AFG
102  1952  Afghanistan              0.091600  AFG
103  1953  Afghanistan              0.106256  AFG

In [25]:
df_c_long = df_c_long[df_c_long['Year'].between(1990, 2024)]
df_p_long = df_p_long[df_p_long['Year'].between(1990, 2024)]

**Restrict to 1990–2024.**

In [26]:
df_p_long.head(5)

     Year      Country  Production_Emissions ISO3
140  1990  Afghanistan              2.024326  AFG
141  1991  Afghanistan              1.914301  AFG
142  1992  Afghanistan              1.482054  AFG
143  1993  Afghanistan              1.486943  AFG
144  1994  Afghanistan              1.453829  AFG

In [27]:
df_c_long.head(5)

    Year  Country  Consumption_Emissions ISO3
35  1990  Albania               5.573464  ALB
36  1991  Albania               4.616082  ALB
37  1992  Albania               2.924931  ALB
38  1993  Albania               2.674815  ALB
39  1994  Albania               2.365348  ALB

In [28]:
df=df_c_long.merge(df_p_long, on=['Year', 'ISO3'], how='inner')

**Join the two emission series.** An inner join on `Year`, `ISO3` *and* `Country`
keeps only country-years present in both. That is deliberate: `transfer` is a
difference between the two measures, so a row missing either side is undefined.

The inner join is also what makes the consumption data the binding constraint —
the resulting panel is roughly the size of `df_c_long`.

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4066 entries, 0 to 4065
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   4066 non-null   int64
 1   Country_x              4066 non-null   str
 2   Consumption_Emissions  4066 non-null   float64
 3   ISO3                   4066 non-null   str
 4   Country_y              4066 non-null   str
 5   Production_Emissions   4066 non-null   float64
dtypes: float64(2), int64(1), str(3)
memory usage: 190.7 KB

**Merged panel.** 4,134 country-year rows, no nulls in either emissions column.

In [30]:
df.head(5)

   Year Country_x  Consumption_Emissions ISO3 Country_y  Production_Emissions
0  1990   Albania               5.573464  ALB   Albania              5.520602
1  1991   Albania               4.616082  ALB   Albania              4.290226
2  1992   Albania               2.924931  ALB   Albania              2.517116
3  1993   Albania               2.674815  ALB   Albania              2.337999
4  1994   Albania               2.365348  ALB   Albania              1.923806

In [31]:
df.head()

   Year Country_x  Consumption_Emissions ISO3 Country_y  Production_Emissions
0  1990   Albania               5.573464  ALB   Albania              5.520602
1  1991   Albania               4.616082  ALB   Albania              4.290226
2  1992   Albania               2.924931  ALB   Albania              2.517116
3  1993   Albania               2.674815  ALB   Albania              2.337999
4  1994   Albania               2.365348  ALB   Albania              1.923806

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4066 entries, 0 to 4065
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   4066 non-null   int64
 1   Country_x              4066 non-null   str
 2   Consumption_Emissions  4066 non-null   float64
 3   ISO3                   4066 non-null   str
 4   Country_y              4066 non-null   str
 5   Production_Emissions   4066 non-null   float64
dtypes: float64(2), int64(1), str(3)
memory usage: 190.7 KB

## GDP/capita data cleaning and conversion to long format

In [33]:
df_gdp_pc= pd.read_csv(gdp_per_capita, skiprows=4)
df_gdp_pc.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,38213.289239,39378.228411,39754.560072,30408.827090,35207.170909,39083.461640,42783.248907,45428.002728,NaN,NaN
1,Africa Eastern and Southern,AFE,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4223.188050,4229.839634,4200.531044,3978.133502,4049.969513,4098.126192,4076.224898,4099.889812,4164.679177,NaN
2,Afghanistan,AFG,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2952.998916,2902.392113,2927.245144,2769.685745,2144.166570,1981.710168,1983.812620,1964.452289,NaN,NaN
3,Africa Western and Central,AFW,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6009.516114,6026.527572,6070.284769,5698.766702,5702.134886,5818.483224,5886.796636,6009.084662,6139.587294,NaN
4,Angola,AGO,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,10565.167648,10154.838923,9712.979449,8904.949006,8720.187687,8750.993630,8597.538788,8752.797471,8760.190820,NaN

**Load GDP per capita.** World Bank CSVs carry four metadata rows before the
header, hence `skiprows=4`. The indicator is PPP-adjusted and in constant 2021
international dollars, so it is comparable both across countries and over time.

In [34]:
years_to_drop = [str(y) for y in range(1960, 1990)]
df_gdp_pc = df_gdp_pc.drop(columns=['Indicator Name', 'Indicator Code'] + years_to_drop)
df_gdp_pc.head()

,Country Name,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,33146.670548,34079.230463,34458.142298,34627.743475,35580.533978,35476.409987,34506.533080,35534.274503,...,38213.289239,39378.228411,39754.560072,30408.827090,35207.170909,39083.461640,42783.248907,45428.002728,NaN,NaN
1,Africa Eastern and Southern,AFE,3520.019233,3425.136430,3252.316888,3127.877714,3099.430165,3155.044828,3247.125124,3291.616658,...,4223.188050,4229.839634,4200.531044,3978.133502,4049.969513,4098.126192,4076.224898,4099.889812,4164.679177,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2952.998916,2902.392113,2927.245144,2769.685745,2144.166570,1981.710168,1983.812620,1964.452289,NaN,NaN
3,Africa Western and Central,AFW,4165.726363,4101.378889,4090.019417,3928.312331,3812.275413,3774.104495,3841.150018,3894.842611,...,6009.516114,6026.527572,6070.284769,5698.766702,5702.134886,5818.483224,5886.796636,6009.084662,6139.587294,NaN
4,Angola,AGO,8366.412716,8170.249394,7445.438367,5481.763868,5377.990350,5981.532576,6565.864794,6808.336281,...,10565.167648,10154.838923,9712.979449,8904.949006,8720.187687,8750.993630,8597.538788,8752.797471,8760.190820,NaN

**Trim to the analysis window.** `Indicator Name`/`Indicator Code` are constant
down the whole file and carry no information; 1960–1989 falls outside the window
set by the emissions data.

In [35]:
df_gdp_pc = df_gdp_pc.drop(columns=['Unnamed: 70'], errors='ignore')

df_gdp_pc_long = df_gdp_pc.melt(
    id_vars=['Country Name', 'Country Code'], var_name='Year', value_name='GDP_per_capita'
)
df_gdp_pc_long['Year'] = df_gdp_pc_long['Year'].astype(int)
df_gdp_pc_long = df_gdp_pc_long.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})
df_gdp_pc_long.head()

                       Country ISO3  Year  GDP_per_capita
0                        Aruba  ABW  1990    33146.670548
1  Africa Eastern and Southern  AFE  1990     3520.019233
2                  Afghanistan  AFG  1990             NaN
3   Africa Western and Central  AFW  1990     4165.726363
4                       Angola  AGO  1990     8366.412716

In [36]:
df_gdp_pc_long = df_gdp_pc_long.sort_values(['Country', 'Year']).reset_index(drop=True)
df_gdp_pc_long.head()

       Country ISO3  Year  GDP_per_capita
0  Afghanistan  AFG  1990             NaN
1  Afghanistan  AFG  1991             NaN
2  Afghanistan  AFG  1992             NaN
3  Afghanistan  AFG  1993             NaN
4  Afghanistan  AFG  1994             NaN

In [37]:
df_gdp_pc_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 9540 entries, 0 to 9539
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         9540 non-null   str
 1   ISO3            9540 non-null   str
 2   Year            9540 non-null   int64
 3   GDP_per_capita  8669 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 298.3 KB

**Coverage check.** 9,540 rows, 8,669 non-null. The ~9% gap is countries with
incomplete GDP series and will propagate into the final panel as missing covariates.

## Data Cleaning of trade freeness data set.

In [38]:
df_trade_openess= pd.read_csv(trade_openess, skiprows=4)

In [39]:
df_trade_openess.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,138.716620,138.824972,137.923249,123.240504,139.510903,160.558141,153.719158,164.138645,NaN,NaN
1,Africa Eastern and Southern,AFE,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,51.760695,54.868090,53.214310,49.343585,54.551332,57.117376,56.283721,54.203271,51.994817,NaN
2,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,46.709895,51.411716,72.885470,66.999578,83.763025,NaN,NaN
3,Africa Western and Central,AFW,Trade (% of GDP),NE.TRD.GNFS.ZS,33.02326,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,44.996325,58.269895,60.371307,54.660403,62.528771,56.538072,53.607013,49.848951,34.646640,NaN

In [40]:
df_trade_openess = df_trade_openess.drop(columns=['Indicator Name', 'Indicator Code'] + years_to_drop)
df_trade_openess.head()

,Country Name,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,171.362098,175.344130,168.781911,...,138.716620,138.824972,137.923249,123.240504,139.510903,160.558141,153.719158,164.138645,NaN,NaN
1,Africa Eastern and Southern,AFE,41.287094,39.781486,40.460789,42.900951,45.509861,47.491919,47.254615,45.115559,...,51.760695,54.868090,53.214310,49.343585,54.551332,57.117376,56.283721,54.203271,51.994817,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,46.709895,51.411716,72.885470,66.999578,83.763025,NaN,NaN
3,Africa Western and Central,AFW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.996325,58.269895,60.371307,54.660403,62.528771,56.538072,53.607013,49.848951,34.646640,NaN

**Trim.** Reuses `years_to_drop` defined in the GDP section, so both World Bank
files are cut to the same window.

In [41]:
df_trade_openess = df_trade_openess.drop(columns=['Unnamed: 70'], errors='ignore')

df_trade_openess_long = df_trade_openess.melt(
    id_vars=['Country Name', 'Country Code'], var_name='Year', value_name='Trade_Openness'
)
df_trade_openess_long['Year'] = df_trade_openess_long['Year'].astype(int)
df_trade_openess_long = df_trade_openess_long.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'})
df_trade_openess_long.head()

                       Country ISO3  Year  Trade_Openness
0                        Aruba  ABW  1990             NaN
1  Africa Eastern and Southern  AFE  1990       41.287094
2                  Afghanistan  AFG  1990             NaN
3   Africa Western and Central  AFW  1990             NaN
4                       Angola  AGO  1990             NaN

**Reshape to long.** Identical treatment to the GDP file, producing the same
`Country`/`ISO3`/`Year` key.

In [42]:
df_trade_openess_long = df_trade_openess_long.sort_values(['Country', 'Year']).reset_index(drop=True)
df_trade_openess_long.head()

       Country ISO3  Year  Trade_Openness
0  Afghanistan  AFG  1990             NaN
1  Afghanistan  AFG  1991             NaN
2  Afghanistan  AFG  1992             NaN
3  Afghanistan  AFG  1993             NaN
4  Afghanistan  AFG  1994             NaN

In [43]:
df_trade_openess_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 9540 entries, 0 to 9539
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country         9540 non-null   str
 1   ISO3            9540 non-null   str
 2   Year            9540 non-null   int64
 3   Trade_Openness  7564 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 298.3 KB

## Population dataset

In [44]:
df_population= pd.read_csv(population)

In [45]:
df_population = df_population[df_population['Year'] >= 1990]
df_population['Population'] = pd.to_numeric(df_population['Population'], errors='coerce')

In [46]:
df_population.info()

<class 'pandas.DataFrame'>
Index: 7700 entries, 20 to 12099
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country/Area  7700 non-null   str
 1   Year          7700 non-null   int64
 2   Unit          7700 non-null   str
 3   Population    7407 non-null   float64
 4   ISO3          7490 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 360.9 KB

In [47]:
parts = (df_population.groupby(['ISO3', 'Year'])['Country/Area'].nunique())
p= parts[parts > 1]
print("Number of unique countries per ISO3 and Year > 1:\n", p)

Number of unique countries per ISO3 and Year > 1:
 ISO3  Year
TZA   1990    2
      1991    2
      1992    2
      1993    2
      1994    2
      1995    2
      1996    2
      1997    2
      1998    2
      1999    2
      2000    2
      2001    2
      2002    2
      2003    2
      2004    2
      2005    2
      2006    2
      2007    2
      2008    2
      2009    2
      2010    2
      2011    2
      2012    2
      2013    2
      2014    2
      2015    2
      2016    2
      2017    2
      2018    2
      2019    2
      2020    2
      2021    2
      2022    2
      2023    2
      2024    2
YEM   1990    3
      1991    3
      1992    3
      1993    3
      1994    3
      1995    3
      1996    3
      1997    3
      1998    3
      1999    3
      2000    3
      2001    3
      2002    3
      2003    3
      2004    3
      2005    3
      2006    3
      2007    3
      2008    3
      2009    3
      2010    3
      2011    3
      2012    3
      2013    3
      2014    3
      2015    3
      2016    3
      2017    3
      2018    3
      2019    3
      2020    3
      2021    3
      2022    3
      2023    3
      2024    3
Name: Country/Area, dtype: int64

## Tanzania and Yemen has duplicated ISO3 and will be checked individually

In [48]:
df_population[df_population['ISO3'] == 'YEM']

                            Country/Area  Year     Unit  Population ISO3
11845                              Yemen  1990  Persons  13887862.0  YEM
11846                              Yemen  1991  Persons  14430201.0  YEM
11847                              Yemen  1992  Persons  14989494.0  YEM
11848                              Yemen  1993  Persons  15563914.0  YEM
11849                              Yemen  1994  Persons  16149147.0  YEM
11850                              Yemen  1995  Persons  16740058.0  YEM
11851                              Yemen  1996  Persons  17313177.0  YEM
11852                              Yemen  1997  Persons  17873936.0  YEM
11853                              Yemen  1998  Persons  18446013.0  YEM
11854                              Yemen  1999  Persons  19029420.0  YEM
11855                              Yemen  2000  Persons  19624141.0  YEM
11856                              Yemen  2001  Persons  20226147.0  YEM
11857                              Yemen  2002  Persons  20835086.0  YEM
11858                              Yemen  2003  Persons  21456379.0  YEM
11859                              Yemen  2004  Persons  22095167.0  YEM
11860                              Yemen  2005  Persons  22790085.0  YEM
11861                              Yemen  2006  Persons  23543083.0  YEM
11862                              Yemen  2007  Persons  24318082.0  YEM
11863                              Yemen  2008  Persons  25111941.0  YEM
11864                              Yemen  2009  Persons  25927724.0  YEM
11865                              Yemen  2010  Persons  26754387.0  YEM
11866                              Yemen  2011  Persons  27582897.0  YEM
11867                              Yemen  2012  Persons  28433647.0  YEM
11868                              Yemen  2013  Persons  29312952.0  YEM
11869                              Yemen  2014  Persons  30226309.0  YEM
11870                              Yemen  2015  Persons  31159379.0  YEM
11871                              Yemen  2016  Persons  32109010.0  YEM
11872                              Yemen  2017  Persons  33090921.0  YEM
11873                              Yemen  2018  Persons  34085182.0  YEM
11874                              Yemen  2019  Persons  35111408.0  YEM
11875                              Yemen  2020  Persons  36134863.0  YEM
11876                              Yemen  2021  Persons  37140230.0  YEM
11877                              Yemen  2022  Persons  38222876.0  YEM
11878                              Yemen  2023  Persons  39390799.0  YEM
11879                              Yemen  2024  Persons  40583164.0  YEM
11900     Yemen: Former Democratic Yemen  1990  Persons   3023960.0  YEM
11901     Yemen: Former Democratic Yemen  1991      ...         NaN  YEM
11902     Yemen: Former Democratic Yemen  1992      ...         NaN  YEM
11903     Yemen: Former Democratic Yemen  1993      ...         NaN  YEM
11904     Yemen: Former Democratic Yemen  1994      ...         NaN  YEM
11905     Yemen: Former Democratic Yemen  1995      ...         NaN  YEM
11906     Yemen: Former Democratic Yemen  1996      ...         NaN  YEM
11907     Yemen: Former Democratic Yemen  1997      ...         NaN  YEM
11908     Yemen: Former Democratic Yemen  1998      ...         NaN  YEM
11909     Yemen: Former Democratic Yemen  1999      ...         NaN  YEM
11910     Yemen: Former Democratic Yemen  2000      ...         NaN  YEM
11911     Yemen: Former Democratic Yemen  2001      ...         NaN  YEM
11912     Yemen: Former Democratic Yemen  2002      ...         NaN  YEM
11913     Yemen: Former Democratic Yemen  2003      ...         NaN  YEM
11914     Yemen: Former Democratic Yemen  2004      ...         NaN  YEM
11915     Yemen: Former Democratic Yemen  2005      ...         NaN  YEM
11916     Yemen: Former Democratic Yemen  2006      ...         NaN  YEM
11917     Yemen: Former Democratic Yemen  2007      ...         NaN  YEM
11918     Yemen: Former Democratic Yemen  2008      ...         NaN  YEM
11919     Yemen: Former Democratic Yemen  2009      ...         NaN  YEM
11920     Yemen: Former Democratic Yemen  2010      ...         NaN  YEM
11921     Yemen: Former Democratic Yemen  2011      ...         NaN  YEM
11922     Yemen: Former Democratic Yemen  2012      ...         NaN  YEM
11923     Yemen: Former Democratic Yemen  2013      ...         NaN  YEM
11924     Yemen: Former Democratic Yemen  2014      ...         NaN  YEM
11925     Yemen: Former Democratic Yemen  2015      ...         NaN  YEM
11926     Yemen: Former Democratic Yemen  2016      ...         NaN  YEM
11927     Yemen: Former Democratic Yemen  2017      ...         NaN  YEM
11928     Yemen: Former Democratic Yemen  2018      ...         NaN  YEM
11929     Yemen: Former Democratic Yemen  2019      ...         NaN  YEM
11930     Yemen: Former Democratic Yemen  2020      ...         NaN  YEM
11931     Yemen: Former Democratic Yemen  2021      ...         NaN  YEM
11932     Yemen: Former Democratic Yemen  2022      ...         NaN  YEM
11933     Yemen: Former Democratic Yemen  2023      ...         NaN  YEM
11934     Yemen: Former Democratic Yemen  2024      ...         NaN  YEM
11955  Yemen: Former Yemen Arab Republic  1990  Persons  10863902.0  YEM
11956  Yemen: Former Yemen Arab Republic  1991      ...         NaN  YEM
11957  Yemen: Former Yemen Arab Republic  1992      ...         NaN  YEM
11958  Yemen: Former Yemen Arab Republic  1993      ...         NaN  YEM
11959  Yemen: Former Yemen Arab Republic  1994      ...         NaN  YEM
11960  Yemen: Former Yemen Arab Republic  1995      ...         NaN  YEM
11961  Yemen: Former Yemen Arab Republic  1996      ...         NaN  YEM
11962  Yemen: Former Yemen Arab Republic  1997      ...         NaN  YEM
11963  Yemen: Former Yemen Arab Republic  1998      ...         NaN  YEM
11964  Yemen: Former Yemen Arab Republic  1999      ...         NaN  YEM
11965  Yemen: Former Yemen Arab Republic  2000      ...         NaN  YEM
11966  Yemen: Former Yemen Arab Republic  2001      ...         NaN  YEM
11967  Yemen: Former Yemen Arab Republic  2002      ...         NaN  YEM
11968  Yemen: Former Yemen Arab Republic  2003      ...         NaN  YEM
11969  Yemen: Former Yemen Arab Republic  2004      ...         NaN  YEM
11970  Yemen: Former Yemen Arab Republic  2005      ...         NaN  YEM
11971  Yemen: Former Yemen Arab Republic  2006      ...         NaN  YEM
11972  Yemen: Former Yemen Arab Republic  2007      ...         NaN  YEM
11973  Yemen: Former Yemen Arab Republic  2008      ...         NaN  YEM
11974  Yemen: Former Yemen Arab Republic  2009      ...         NaN  YEM
11975  Yemen: Former Yemen Arab Republic  2010      ...         NaN  YEM
11976  Yemen: Former Yemen Arab Republic  2011      ...         NaN  YEM
11977  Yemen: Former Yemen Arab Republic  2012      ...         NaN  YEM
11978  Yemen: Former Yemen Arab Republic  2013      ...         NaN  YEM
11979  Yemen: Former Yemen Arab Republic  2014      ...         NaN  YEM
11980  Yemen: Former Yemen Arab Republic  2015      ...         NaN  YEM
11981  Yemen: Former Yemen Arab Republic  2016      ...         NaN  YEM
11982  Yemen: Former Yemen Arab Republic  2017      ...         NaN  YEM
11983  Yemen: Former Yemen Arab Republic  2018      ...         NaN  YEM
11984  Yemen: Former Yemen Arab Republic  2019      ...         NaN  YEM
11985  Yemen: Former Yemen Arab Republic  2020      ...         NaN  YEM
11986  Yemen: Former Yemen Arab Republic  2021      ...         NaN  YEM
11987  Yemen: Former Yemen Arab Republic  2022      ...         NaN  YEM
11988  Yemen: Former Yemen Arab Republic  2023      ...         NaN  YEM
11989  Yemen: Former Yemen Arab Republic  2024      ...         NaN  YEM

In [49]:
for iso in p.index.get_level_values('ISO3').unique():
    names = sorted(df_population.loc[df_population['ISO3'] == iso, 'Country/Area'].unique())
    print(f'  {iso}: {names}')

  TZA: ['United Republic of Tanzania: Mainland', 'United Republic of Tanzania: Zanzibar']
  YEM: ['Yemen', 'Yemen: Former Democratic Yemen', 'Yemen: Former Yemen Arab Republic']

In [50]:
tan= df_population[df_population['Country/Area'].isin(['United Republic of Tanzania: Mainland', 'United Republic of Tanzania: Zanzibar'])]

aggregated_tan = tan.groupby(['Year'], as_index=False).agg({'Population': 'sum'})

df_population = pd.concat([df_population[~df_population['ISO3'].isin(['TZA'])], aggregated_tan.assign(ISO3='TZA', **{'Country/Area': 'United Republic of Tanzania'})], ignore_index=True)

In [51]:
df_population.info()

<class 'pandas.DataFrame'>
RangeIndex: 7665 entries, 0 to 7664
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country/Area  7665 non-null   str
 1   Year          7665 non-null   int64
 2   Unit          7630 non-null   str
 3   Population    7372 non-null   float64
 4   ISO3          7455 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 299.5 KB

**Structure check.** Note `Population` loads as a **string**, not an integer —
fixed further down, before the data is written out. `ISO3` has 210 nulls, which
are non-sovereign territories and aggregates; the inner joins drop them.

In [52]:
df_population.head(40)

   Country/Area  Year     Unit  Population ISO3
0   Afghanistan  1990  Persons  12045660.0  AFG
1   Afghanistan  1991  Persons  12238879.0  AFG
2   Afghanistan  1992  Persons  13278974.0  AFG
3   Afghanistan  1993  Persons  14943172.0  AFG
4   Afghanistan  1994  Persons  16250794.0  AFG
5   Afghanistan  1995  Persons  17065836.0  AFG
6   Afghanistan  1996  Persons  17763266.0  AFG
7   Afghanistan  1997  Persons  18452091.0  AFG
8   Afghanistan  1998  Persons  19159996.0  AFG
9   Afghanistan  1999  Persons  19887785.0  AFG
10  Afghanistan  2000  Persons  20130327.0  AFG
11  Afghanistan  2001  Persons  20284307.0  AFG
12  Afghanistan  2002  Persons  21378117.0  AFG
13  Afghanistan  2003  Persons  22733049.0  AFG
14  Afghanistan  2004  Persons  23560654.0  AFG
15  Afghanistan  2005  Persons  24404567.0  AFG
16  Afghanistan  2006  Persons  25424094.0  AFG
17  Afghanistan  2007  Persons  25909852.0  AFG
18  Afghanistan  2008  Persons  26482622.0  AFG
19  Afghanistan  2009  Persons  27466101.0  AFG
20  Afghanistan  2010  Persons  28284089.0  AFG
21  Afghanistan  2011  Persons  29347708.0  AFG
22  Afghanistan  2012  Persons  30560034.0  AFG
23  Afghanistan  2013  Persons  31622704.0  AFG
24  Afghanistan  2014  Persons  32792523.0  AFG
25  Afghanistan  2015  Persons  33831764.0  AFG
26  Afghanistan  2016  Persons  34700612.0  AFG
27  Afghanistan  2017  Persons  35688935.0  AFG
28  Afghanistan  2018  Persons  36743039.0  AFG
29  Afghanistan  2019  Persons  37856121.0  AFG
30  Afghanistan  2020  Persons  39068979.0  AFG
31  Afghanistan  2021  Persons  40000412.0  AFG
32  Afghanistan  2022  Persons  40578842.0  AFG
33  Afghanistan  2023  Persons  41454761.0  AFG
34  Afghanistan  2024  Persons  42647492.0  AFG
35      Albania  1990  Persons   3277966.0  ALB
36      Albania  1991  Persons   3282602.0  ALB
37      Albania  1992  Persons   3282501.0  ALB
38      Albania  1993  Persons   3277825.0  ALB
39      Albania  1994  Persons   3269410.0  ALB

## Merging population gdp/capita and trade freeness together

In [ ]:
df2 = df_gdp_pc_long.merge(df_trade_openess_long, on=['ISO3', 'Year'], how='inner')
df2 = df2.merge(df_population, on=['ISO3', 'Year'], how='inner')

**Assemble the covariates.** GDP per capita, then trade openness, then population —
joined on `ISO3` + `Year` only, never on country name, since the three sources spell
names differently.

These are inner joins, so a country must appear in all three files to survive.
`Country_x`/`Country_y` are the redundant name columns; they are dropped after the
final merge.

The assertion enforces the panel's key invariant: one row per country-year. This is
the check that would have caught the Tanzania duplication at source.

In [54]:
df2 = df2.sort_values(['Country_x', 'Year']).reset_index(drop=True)
df2.head()

,Country_x,ISO3,Year,GDP_per_capita,Country_y,Trade_Openness,Country/Area,Unit,Population
0,Afghanistan,AFG,1990,NaN,Afghanistan,NaN,Afghanistan,Persons,12045660.0
1,Afghanistan,AFG,1991,NaN,Afghanistan,NaN,Afghanistan,Persons,12238879.0
2,Afghanistan,AFG,1992,NaN,Afghanistan,NaN,Afghanistan,Persons,13278974.0
3,Afghanistan,AFG,1993,NaN,Afghanistan,NaN,Afghanistan,Persons,14943172.0
4,Afghanistan,AFG,1994,NaN,Afghanistan,NaN,Afghanistan,Persons,16250794.0

**Sort.** Cosmetic.

## Merging df1 and df2

In [55]:
df1 = df
df_final = df1.merge(df2, on=['ISO3', 'Year'], how='inner')


df_final.head()

,Year,Country_x_x,Consumption_Emissions,ISO3,Country_y_x,Production_Emissions,Country_x_y,GDP_per_capita,Country_y_y,Trade_Openness,Country/Area,Unit,Population
0,1990,Albania,5.573464,ALB,Albania,5.520602,Albania,5560.833935,Albania,39.436963,Albania,Persons,3277966.0
1,1991,Albania,4.616082,ALB,Albania,4.290226,Albania,4027.888807,Albania,36.070520,Albania,Persons,3282602.0
2,1992,Albania,2.924931,ALB,Albania,2.517116,Albania,3761.139808,Albania,108.785472,Albania,Persons,3282501.0
3,1993,Albania,2.674815,ALB,Albania,2.337999,Albania,4145.902505,Albania,80.518333,Albania,Persons,3277825.0
4,1994,Albania,2.365348,ALB,Albania,1.923806,Albania,4517.780079,Albania,53.102585,Albania,Persons,3269410.0

**Final merge.** The emissions panel joined to the covariate panel on `ISO3` + `Year`,
with the same uniqueness guard. Inner again, so the result is the intersection of every
source.

In [56]:
df_final = df_final[[ 'Country/Area', 'ISO3', 'Year', 'Consumption_Emissions', 'Production_Emissions', 'GDP_per_capita', 'Trade_Openness', 'Population']]
df_final = df_final.rename(columns={'Country/Area': 'Country'})
df_final.head()

,Country,ISO3,Year,Consumption_Emissions,Production_Emissions,GDP_per_capita,Trade_Openness,Population
0,Albania,ALB,1990,5.573464,5.520602,5560.833935,39.436963,3277966.0
1,Albania,ALB,1991,4.616082,4.290226,4027.888807,36.070520,3282602.0
2,Albania,ALB,1992,2.924931,2.517116,3761.139808,108.785472,3282501.0
3,Albania,ALB,1993,2.674815,2.337999,4145.902505,80.518333,3277825.0
4,Albania,ALB,1994,2.365348,1.923806,4517.780079,53.102585,3269410.0

**Select and order the analysis columns.** Discards the three duplicate country
name columns and the constant `Unit` column, keeping one clean `Country` label.

In [57]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 4032 entries, 0 to 4031
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                4032 non-null   str
 1   ISO3                   4032 non-null   str
 2   Year                   4032 non-null   int64
 3   Consumption_Emissions  4032 non-null   float64
 4   Production_Emissions   4032 non-null   float64
 5   GDP_per_capita         3998 non-null   float64
 6   Trade_Openness         3805 non-null   float64
 7   Population             4032 non-null   float64
dtypes: float64(5), int64(1), str(2)
memory usage: 252.1 KB

**Pre-cast check.** 4,066 rows. `GDP_per_capita` is 34 short and
`Trade_Openness` 227 short of complete — these gaps are real and need an explicit
decision at estimation time (listwise deletion vs. a restricted sample). Note
`Population` is string which will be converted to int.

In [58]:
df_final['Population'] = pd.to_numeric(df_final['Population'], errors='raise').astype('int64')

In [59]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 4032 entries, 0 to 4031
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                4032 non-null   str
 1   ISO3                   4032 non-null   str
 2   Year                   4032 non-null   int64
 3   Consumption_Emissions  4032 non-null   float64
 4   Production_Emissions   4032 non-null   float64
 5   GDP_per_capita         3998 non-null   float64
 6   Trade_Openness         3805 non-null   float64
 7   Population             4032 non-null   int64
dtypes: float64(4), int64(2), str(2)
memory usage: 252.1 KB

**Confirm the cast.** `Population` is now `int64`.

# **Treatment Block**

In [ ]:
ANNEX_B = {
    'AUS','AUT','BEL','BGR','CAN','HRV','CZE','DNK','EST','FIN','FRA','DEU',
    'GRC','HUN','ISL','IRL','ITA','JPN','LVA','LIE','LTU','LUX','MCO','NLD',
    'NZL','NOR','POL','PRT','ROU','RUS','SVK','SVN','ESP','SWE','CHE','UKR','GBR',
}  # USA excluded: as theysigned but never-treated.

# Catch typos/format drift instead of silently coding a treated country as control
missing = ANNEX_B - set(df_final['ISO3'])
assert missing <= {'ISL','LIE','MCO'}, f"unexpected Annex B codes absent: {missing}"

KYOTO_ENTRY_INTO_FORCE  = 2005   # treaty legally binding from 16 Feb 2005
FIRST_COMMITMENT_PERIOD = 2008   # 2008-2012 compliance window

df_final['annex_b']     = df_final['ISO3'].isin(ANNEX_B).astype(int)
df_final['first_treat'] = df_final['annex_b'] * KYOTO_ENTRY_INTO_FORCE  # 0 = never-treated
df_final['post']        = (df_final['Year'] >= KYOTO_ENTRY_INTO_FORCE).astype(int)
df_final['rel_year']    = np.where(df_final['annex_b'] == 1,
                                   df_final['Year'] - KYOTO_ENTRY_INTO_FORCE, np.nan)  # event-study axis

# Same coding anchored on 2008, for the timing robustness check.
df_final['first_treat_2008'] = df_final['annex_b'] * FIRST_COMMITMENT_PERIOD
df_final['post_2008']        = (df_final['Year'] >= FIRST_COMMITMENT_PERIOD).astype(int)
df_final['rel_year_2008']    = np.where(df_final['annex_b'] == 1,
                                        df_final['Year'] - FIRST_COMMITMENT_PERIOD, np.nan)

# C&S needs a numeric unit id
df_final['country_id'] = df_final['ISO3'].map(
    {iso: i for i, iso in enumerate(sorted(df_final['ISO3'].unique()))}
)

print(df_final.groupby('annex_b')['ISO3'].nunique())         
print(df_final.groupby('first_treat')['ISO3'].nunique())

annex_b
0    85
1    34
Name: ISO3, dtype: int64
first_treat
0       85
2005    34
Name: ISO3, dtype: int64

**Treatment coding for the DiD.**

`ANNEX_B` is the set of countries with binding first-period Kyoto targets. The USA
is deliberately excluded: it signed but never ratified, so it never faced a binding
target and belongs in the never-treated control group. The assertion guards against
a code silently dropping out of the panel — `ISL`, `LIE` and `MCO` are allowed to be
absent because they are too small to appear in all source files.

**On the timing.** Two dates are defensible and the choice is a real modelling
decision, not a detail:

- **2005** — the treaty entered into force on 16 Feb 2005, so this is when the obligation became binding and anticipation effects could start.
- **2008** — the first commitment period (2008–2012) is when compliance was actually measured.

2005 is the main specification; `first_treat_2008`, `post_2008` and `rel_year_2008`
carry the alternative so the robustness check is a one-line change at estimation
rather than a re-run of this notebook.

**A note on the estimator.** `first_treat` follows the Callaway–Sant'Anna
convention (`0` = never-treated). But every treated unit here shares a single
adoption date, so there is no staggered adoption — C&S collapses to essentially a
2×2 design and buys little over a two-way fixed effects model with an event-study
plot on `rel_year`. Both should give the same answer; TWFE is the simpler thing to
defend in the write-up.

In [61]:
df_final.head()

,Country,ISO3,Year,Consumption_Emissions,Production_Emissions,GDP_per_capita,Trade_Openness,Population,annex_b,first_treat,post,rel_year,first_treat_2008,post_2008,rel_year_2008,country_id
0,Albania,ALB,1990,5.573464,5.520602,5560.833935,39.436963,3277966,0,0,0,NaN,0,0,NaN,0
1,Albania,ALB,1991,4.616082,4.290226,4027.888807,36.070520,3282602,0,0,0,NaN,0,0,NaN,0
2,Albania,ALB,1992,2.924931,2.517116,3761.139808,108.785472,3282501,0,0,0,NaN,0,0,NaN,0
3,Albania,ALB,1993,2.674815,2.337999,4145.902505,80.518333,3277825,0,0,0,NaN,0,0,NaN,0
4,Albania,ALB,1994,2.365348,1.923806,4517.780079,53.102585,3269410,0,0,0,NaN,0,0,NaN,0

In [63]:

df_final = df_final.sort_values(['ISO3', 'Year']).reset_index(drop=True)

df_final.to_csv(out_final, index=False)